import type { Guide, LocalizedText, Person, Story } from "./types";

const t = (en: string, es: string): LocalizedText => ({ en, es });

const peopleSeed: Omit<Person, "image" | "links">[] = [
  { slug: "chen-rui", name: "Chen Rui", identity: t("Urban mobility researcher", "Investigador de movilidad urbana"), city: t("Shanghai", "Shanghái"), topics: [t("Mobility", "Movilidad"), t("City life", "Vida urbana")], contribution: t("Driving in Shanghai: licences, permits and the first week", "Conducir en Shanghái: licencias, permisos y la primera semana"), introduction: t("I study how rules meet ordinary movement: the first commute, the first school run, and the small decisions that make a city legible.", "Estudio cómo las normas se encuentran con el movimiento cotidiano: el primer trayecto, el camino a la escuela y las pequeñas decisiones que vuelven legible una ciudad.") },
  { slug: "lin-mei", name: "Lin Mei", identity: t("Food systems writer", "Autora sobre sistemas alimentarios"), city: t("Hangzhou", "Hangzhou"), topics: [t("Food", "Alimentación"), t("Work", "Trabajo")], contribution: t("What a neighborhood breakfast tells us about work", "Lo que un desayuno de barrio cuenta sobre el trabajo"), introduction: t("I follow food from farms and wholesale markets into the kitchens where daily routines take shape.", "Sigo los alimentos desde las granjas y mercados mayoristas hasta las cocinas donde se forman las rutinas diarias.") },
  { slug: "zhao-jian", name: "Zhao Jian", identity: t("Independent music producer", "Productor musical independiente"), city: t("Chengdu", "Chengdu"), topics: [t("Music", "Música"), t("Nightlife", "Vida nocturna")], contribution: t("The rooms where Chengdu’s new music takes shape", "Los espacios donde toma forma la nueva música de Chengdu"), introduction: t("I record small scenes, rehearsal rooms and the people building music outside the largest stages.", "Documento escenas pequeñas, salas de ensayo y a quienes hacen música fuera de los grandes escenarios.") },
  { slug: "wu-yan", name: "Wu Yan", identity: t("Community physician", "Médica comunitaria"), city: t("Guangzhou", "Cantón"), topics: [t("Health", "Salud"), t("Families", "Familias")], contribution: t("Finding everyday care in a new city", "Encontrar atención cotidiana en una ciudad nueva"), introduction: t("My work sits between clinical practice and the practical questions families ask before an appointment.", "Mi trabajo está entre la práctica clínica y las preguntas concretas que hacen las familias antes de una consulta.") },
  { slug: "he-tao", name: "He Tao", identity: t("Architect and conservation researcher", "Arquitecto e investigador de conservación"), city: t("Suzhou", "Suzhou"), topics: [t("Architecture", "Arquitectura"), t("Heritage", "Patrimonio")], contribution: t("Living with old buildings rather than looking at them", "Vivir con edificios antiguos en vez de solo mirarlos"), introduction: t("I write about buildings as places of work, repair and ordinary negotiation.", "Escribo sobre los edificios como lugares de trabajo, reparación y negociación cotidiana.") },
  { slug: "sun-qiao", name: "Sun Qiao", identity: t("Ceramic artist", "Artista de cerámica"), city: t("Jingdezhen", "Jingdezhen"), topics: [t("Craft", "Oficios"), t("Making", "Creación")], contribution: t("A working kiln, from clay delivery to firing day", "Un horno en marcha, desde la llegada de la arcilla hasta la cocción"), introduction: t("My studio practice begins with materials, tools and the pace shared by many hands.", "Mi práctica comienza con los materiales, las herramientas y el ritmo compartido por muchas manos.") },
  { slug: "guo-lan", name: "Guo Lan", identity: t("Market vendor and oral historian", "Comerciante e historiadora oral"), city: t("Kunming", "Kunming"), topics: [t("Markets", "Mercados"), t("Memory", "Memoria")], contribution: t("The market names that never made it onto a map", "Los nombres del mercado que nunca llegaron al mapa"), introduction: t("I collect the names, routes and working memories held by people who have spent decades in the same market.", "Recojo los nombres, rutas y memorias de trabajo de quienes llevan décadas en el mismo mercado.") },
  { slug: "ma-yunfei", name: "Ma Yunfei", identity: t("Workshop owner", "Dueño de un taller"), city: t("Shenyang", "Shenyang"), topics: [t("Industry", "Industria"), t("Small business", "Pequeña empresa")], contribution: t("What a repair shop keeps in circulation", "Lo que un taller de reparación mantiene en circulación"), introduction: t("I repair machines and write about the practical knowledge that travels with them.", "Reparo máquinas y escribo sobre el conocimiento práctico que viaja con ellas.") },
  { slug: "tang-xin", name: "Tang Xin", identity: t("Librarian", "Bibliotecaria"), city: t("Nanjing", "Nankín"), topics: [t("Books", "Libros"), t("Education", "Educación")], contribution: t("A public library after the school bell", "Una biblioteca pública después de la salida escolar"), introduction: t("I observe how readers use public space when study, leisure and family time overlap.", "Observo cómo los lectores usan el espacio público cuando se cruzan el estudio, el ocio y la vida familiar.") },
  { slug: "liu-bo", name: "Liu Bo", identity: t("River ecologist", "Ecólogo fluvial"), city: t("Wuhan", "Wuhan"), topics: [t("Environment", "Medio ambiente"), t("Rivers", "Ríos")], contribution: t("Reading the Yangtze from a neighborhood path", "Leer el Yangtsé desde un sendero de barrio"), introduction: t("I connect field observations with the ordinary ways people notice a changing river.", "Conecto las observaciones de campo con las formas cotidianas de percibir un río que cambia.") },
  { slug: "xu-min", name: "Xu Min", identity: t("Retired railway engineer", "Ingeniero ferroviario jubilado"), city: t("Xi’an", "Xi'an"), topics: [t("Rail", "Ferrocarril"), t("Engineering", "Ingeniería")], contribution: t("The timetable as a record of changing distance", "El horario como registro de una distancia cambiante"), introduction: t("I spent four decades around railways and now document the routines hidden behind a journey.", "Pasé cuatro décadas alrededor del ferrocarril y ahora documento las rutinas ocultas detrás de un viaje.") },
  { slug: "fang-jie", name: "Fang Jie", identity: t("Home cook and recipe editor", "Cocinera y editora de recetas"), city: t("Fuzhou", "Fuzhou"), topics: [t("Home cooking", "Cocina casera"), t("Migration", "Migración")], contribution: t("Recipes that changed when the family moved", "Recetas que cambiaron cuando la familia se mudó"), introduction: t("I edit recipes as living records, attentive to what changes when ingredients, homes and generations move.", "Edito recetas como registros vivos, atenta a lo que cambia cuando se mueven los ingredientes, los hogares y las generaciones.") },
  { slug: "gao-zhe", name: "Gao Zhe", identity: t("Robotics engineer", "Ingeniero de robótica"), city: t("Shenzhen", "Shenzhen"), topics: [t("Technology", "Tecnología"), t("Manufacturing", "Manufactura")], contribution: t("Inside a small robotics lab before a product launch", "Dentro de un pequeño laboratorio de robótica antes de un lanzamiento"), introduction: t("I explain the work between a prototype and a production line, including the revisions that disappear from the final object.", "Explico el trabajo entre un prototipo y una línea de producción, incluidas las revisiones que desaparecen del objeto final.") },
  { slug: "qian-yu", name: "Qian Yu", identity: t("Guesthouse keeper", "Anfitriona de una casa rural"), city: t("Dali", "Dali"), topics: [t("Hospitality", "Hospitalidad"), t("Rural life", "Vida rural")], contribution: t("A guesthouse year beyond the holiday season", "Un año en una casa rural más allá de las vacaciones"), introduction: t("I write from the courtyard where visitors, neighbors and seasonal work share the same calendar.", "Escribo desde el patio donde visitantes, vecinos y trabajo estacional comparten el mismo calendario.") },
  { slug: "luo-han", name: "Luo Han", identity: t("Commercial lawyer", "Abogado mercantil"), city: t("Beijing", "Pekín"), topics: [t("Business", "Negocios"), t("Contracts", "Contratos")], contribution: t("The questions to ask before a first partnership", "Las preguntas antes de una primera alianza"), introduction: t("I translate common contract problems into the decisions people need to make before a deal advances.", "Traduzco problemas contractuales comunes en las decisiones que conviene tomar antes de que avance un acuerdo.") },
  { slug: "pei-ning", name: "Pei Ning", identity: t("Dance teacher", "Profesora de danza"), city: t("Changsha", "Changsha"), topics: [t("Dance", "Danza"), t("Youth", "Juventud")], contribution: t("A rehearsal room at the end of a long school day", "Una sala de ensayo al final de un largo día escolar"), introduction: t("I write about discipline, bodies and the quiet social life that grows around rehearsal.", "Escribo sobre disciplina, cuerpos y la vida social silenciosa que crece alrededor del ensayo.") },
  { slug: "song-yi", name: "Song Yi", identity: t("Bookseller", "Librera"), city: t("Qingdao", "Qingdao"), topics: [t("Books", "Libros"), t("Coastal cities", "Ciudades costeras")], contribution: t("What stays on the shelf through a changing season", "Lo que permanece en la estantería durante una temporada cambiante"), introduction: t("My bookstore is a place to watch which questions return and which arrive for the first time.", "Mi librería permite ver qué preguntas regresan y cuáles aparecen por primera vez.") },
  { slug: "deng-ke", name: "Deng Ke", identity: t("Transit planner", "Planificador de transporte"), city: t("Chongqing", "Chongqing"), topics: [t("Mobility", "Movilidad"), t("Terrain", "Territorio")], contribution: t("Planning a commute in a city built on slopes", "Planificar un trayecto en una ciudad construida sobre laderas"), introduction: t("I study the gap between a route on paper and the effort a journey asks of a body.", "Estudio la distancia entre una ruta sobre el papel y el esfuerzo que un viaje exige al cuerpo.") },
  { slug: "mo-yue", name: "Mo Yue", identity: t("Spatial designer", "Diseñadora espacial"), city: t("Xiamen", "Xiamen"), topics: [t("Design", "Diseño"), t("Public space", "Espacio público")], contribution: t("Small seats, shade and the life of a public square", "Asientos, sombra y la vida de una plaza pública"), introduction: t("I pay attention to the details that decide whether a public place supports a short pause or a longer stay.", "Me fijo en los detalles que deciden si un espacio público permite una pausa breve o una estancia larga.") },
  { slug: "zhang-de", name: "Zhang De", identity: t("Restaurant owner", "Dueño de un restaurante"), city: t("Harbin", "Harbin"), topics: [t("Food", "Alimentación"), t("Weather", "Clima")], contribution: t("Running a dining room through the northern winter", "Mantener un comedor durante el invierno del norte"), introduction: t("I write about food service as logistics, hospitality and adaptation to a severe season.", "Escribo sobre la restauración como logística, hospitalidad y adaptación a una estación exigente.") },
  { slug: "zhou-ping", name: "Zhou Ping", identity: t("Building surveyor", "Inspector de edificios"), city: t("Tianjin", "Tianjin"), topics: [t("Housing", "Vivienda"), t("Architecture", "Arquitectura")], contribution: t("The maintenance history written into an apartment block", "La historia de mantenimiento escrita en un bloque de viviendas"), introduction: t("I read buildings through repairs, materials and the conversations that happen around shared walls.", "Leo los edificios a través de reparaciones, materiales y conversaciones alrededor de muros compartidos.") },
  { slug: "ye-xia", name: "Ye Xia", identity: t("Tea grower", "Cultivadora de té"), city: t("Anxi", "Anxi"), topics: [t("Agriculture", "Agricultura"), t("Climate", "Clima")], contribution: t("A tea season measured in small weather changes", "Una temporada de té medida en pequeños cambios del tiempo"), introduction: t("I document the decisions growers make when familiar seasonal signals become less reliable.", "Documento las decisiones de los agricultores cuando las señales estacionales conocidas se vuelven menos fiables.") },
  { slug: "jiang-an", name: "Jiang An", identity: t("Violin teacher", "Profesor de violín"), city: t("Wuxi", "Wuxi"), topics: [t("Music", "Música"), t("Education", "Educación")], contribution: t("What a beginner hears before the first melody", "Lo que oye un principiante antes de la primera melodía"), introduction: t("I write about listening, repetition and the small adjustments that make learning audible.", "Escribo sobre escucha, repetición y los pequeños ajustes que vuelven audible el aprendizaje.") },
  { slug: "rao-sheng", name: "Rao Sheng", identity: t("Boat repairer", "Reparador de embarcaciones"), city: t("Zhoushan", "Zhoushan"), topics: [t("Coast", "Costa"), t("Craft", "Oficios")], contribution: t("The winter repair season at a working harbor", "La temporada invernal de reparaciones en un puerto activo"), introduction: t("I repair working boats and record the knowledge shared between crews, yards and changing seas.", "Reparo barcos de trabajo y registro el conocimiento compartido entre tripulaciones, astilleros y mares cambiantes.") },
];

export const people: Person[] = peopleSeed.map((person, index) => ({
  ...person,
  image: `/images/fixtures/portrait-${index < 12 ? "a" : "b"}-${String(index % 12).padStart(2, "0")}.webp`,
  links: [
    { label: "Website", href: "https://example.com" },
    { label: "Newsletter", href: "https://example.com/newsletter" },
  ],
}));

export const stories: Story[] = [
  { slug: "morning-routes-shanghai", kind: "Story", title: t("The morning routes that make a neighborhood", "Las rutas matinales que forman un barrio"), summary: t("A street-level account of school runs, breakfast stalls and the first deliveries of the day.", "Una mirada a pie de calle sobre trayectos escolares, puestos de desayuno y las primeras entregas del día."), authorSlug: "chen-rui", date: "2026-07-19", purpose: t("Understand", "Comprender") },
  { slug: "market-names-kunming", kind: "Story", title: t("The market names that never made it onto a map", "Los nombres del mercado que nunca llegaron al mapa"), summary: t("Guo Lan records a working geography held in memory and conversation.", "Guo Lan registra una geografía de trabajo sostenida por la memoria y la conversación."), authorSlug: "guo-lan", date: "2026-07-17", purpose: t("Understand", "Comprender") },
  { slug: "chengdu-rehearsal-rooms", kind: "Story", title: t("The rooms where Chengdu’s new music takes shape", "Los espacios donde toma forma la nueva música de Chengdu"), summary: t("Three rehearsal rooms, one week, and the people keeping them open.", "Tres salas de ensayo, una semana y las personas que las mantienen abiertas."), authorSlug: "zhao-jian", date: "2026-07-14", purpose: t("Visit", "Visitar") },
  { slug: "jingdezhen-firing-day", kind: "Story", title: t("A working kiln, from clay delivery to firing day", "Un horno en marcha, desde la llegada de la arcilla hasta la cocción"), summary: t("Sun Qiao follows the tools, timing and shared labor of one firing.", "Sun Qiao sigue las herramientas, los tiempos y el trabajo compartido de una cocción."), authorSlug: "sun-qiao", date: "2026-07-10", purpose: t("Work", "Trabajar") },
  { slug: "yangtze-neighborhood-path", kind: "Place", title: t("Reading the Yangtze from a neighborhood path", "Leer el Yangtsé desde un sendero de barrio"), summary: t("Liu Bo traces environmental change through a path used every day.", "Liu Bo sigue el cambio ambiental a través de un sendero usado cada día."), authorSlug: "liu-bo", date: "2026-07-08", purpose: t("Live", "Vivir") },
];

export const drivingGuide: Guide = {
  slug: "driving-in-shanghai",
  kind: "Guide",
  title: t("Driving in Shanghai: licences, permits and the first week", "Conducir en Shanghái: licencias, permisos y la primera semana"),
  summary: t("The documents, appointments and street-level habits that matter before your first drive.", "Los documentos, las citas y los hábitos de calle que importan antes de conducir por primera vez."),
  authorSlug: "chen-rui",
  date: "2026-06-28",
  reviewed: "2026-07-21",
  purpose: t("Live", "Vivir"),
  sections: [
    { heading: t("Before you book an appointment", "Antes de reservar una cita"), body: [t("Confirm which licence conversion route applies to your stay and keep the name on every document consistent. Appointment availability and accepted translations can change by district.", "Confirma qué vía de conversión corresponde a tu estancia y mantén el mismo nombre en todos los documentos. La disponibilidad de citas y las traducciones aceptadas pueden cambiar según el distrito."), t("Bring the original documents and the copies requested by the office handling your application. A digital scan may help with reference, but it does not replace the required paper set.", "Lleva los documentos originales y las copias solicitadas por la oficina responsable. Un escaneo digital puede servir de referencia, pero no sustituye el juego de documentos requerido.")] },
    { heading: t("The first week on the road", "La primera semana al volante"), body: [t("Plan short routes first. Lane markings, protected turns, scooter traffic and parking entrances demand more attention than distance alone suggests.", "Empieza con trayectos cortos. Las marcas de carril, los giros protegidos, el tráfico de motos y los accesos a aparcamientos exigen más atención de la que sugiere la distancia."), t("Keep the vehicle documents accessible and check the rules for the roads you use most often. Local restrictions and enforcement windows can be more important than the fastest route.", "Mantén accesibles los documentos del vehículo y revisa las normas de las vías que usas con más frecuencia. Las restricciones locales y sus horarios pueden importar más que la ruta más rápida.")] },
    { heading: t("What to verify again", "Qué conviene volver a comprobar"), body: [t("Treat fees, office locations and processing times as changeable. Recheck them with the responsible authority before travel or payment.", "Considera cambiantes las tasas, las ubicaciones de las oficinas y los plazos. Vuelve a comprobarlos con la autoridad responsable antes de desplazarte o pagar.")] },
  ],
  sources: [t("Shanghai traffic management service information, reviewed 21 July 2026", "Información del servicio de gestión de tráfico de Shanghái, revisada el 21 de julio de 2026"), t("Field notes from two licence-conversion appointments, June 2026", "Notas de campo de dos citas de conversión de licencia, junio de 2026")],
};

export const guides: Guide[] = [drivingGuide];
