/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    people: Person;
    'person-revisions': PersonRevision;
    taxonomies: Taxonomy;
    media: Media;
    articles: Article;
    places: Place;
    'workflow-events': WorkflowEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'person-revisions': PersonRevisionsSelect<false> | PersonRevisionsSelect<true>;
    taxonomies: TaxonomiesSelect<false> | TaxonomiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    'workflow-events': WorkflowEventsSelect<false> | WorkflowEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    workspace: WorkspaceWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  accountStatus: 'active' | 'paused';
  role: 'author' | 'editor' | 'super_admin';
  displayName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  portrait?: (number | null) | Media;
  languages?: ('en' | 'es')[] | null;
  topics?: (number | Taxonomy)[] | null;
  identity?: string | null;
  city?: string | null;
  introduction?: string | null;
  identityEs?: string | null;
  cityEs?: string | null;
  introductionEs?: string | null;
  links?:
    | {
        type:
          'personal_site' | 'newsletter' | 'youtube' | 'linkedin' | 'x' | 'instagram' | 'github' | 'email' | 'other';
        label: string;
        labelEs?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  user?: (number | null) | User;
  profileStatus: 'draft' | 'public' | 'paused';
  authorApprovalRecordedAt?: string | null;
  profilePublishedAt?: string | null;
  spotlightExcluded?: boolean | null;
  spotlightPinnedUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  uploadedBy?: (number | null) | User;
  memberUsePublishedAt?: string | null;
  publicUseApprovedAt?: string | null;
  publicUseApprovedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies".
 */
export interface Taxonomy {
  id: number;
  dimension: 'purpose' | 'topic' | 'geography' | 'situation';
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person-revisions".
 */
export interface PersonRevision {
  id: number;
  person: number | Person;
  proposer: number | User;
  openPersonKey?: string | null;
  proposedIdentity: string;
  proposedIntroduction: string;
  proposedCity: string;
  proposedPortrait?: (number | null) | Media;
  proposedLanguages: ('en' | 'es')[];
  proposedTopics?: (number | Taxonomy)[] | null;
  proposedLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'submitted' | 'changes_requested' | 'applied';
  editorNote?: string | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  reviewer?: (number | null) | User;
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  summary?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  locale: 'en' | 'es';
  slug: string;
  author: number | Person;
  format?: ('guide' | 'reporting' | 'analysis' | 'first_person' | 'update') | null;
  purposes?: (number | Taxonomy)[] | null;
  topics?: (number | Taxonomy)[] | null;
  geographies?: (number | Taxonomy)[] | null;
  situations?: (number | Taxonomy)[] | null;
  sourceNotes?:
    | {
        label: string;
        url?: string | null;
        check?: string | null;
        id?: string | null;
      }[]
    | null;
  editorComments?:
    | {
        anchor: string;
        message: string;
        resolved?: boolean | null;
        createdBy: number | User;
        id?: string | null;
      }[]
    | null;
  assignedEditor?: (number | null) | User;
  freshnessDate?: string | null;
  publishedAt?: string | null;
  homepagePlacement?: ('none' | 'lead' | 'selected') | null;
  homepageStartsAt?: string | null;
  homepageEndsAt?: string | null;
  translationGroup: string;
  owner: number | User;
  publicationStatus: 'draft' | 'published' | 'withdrawn';
  curationStatus: 'not_selected' | 'selected' | 'editing' | 'curated' | 'needs_recheck' | 'removed';
  workflowStatus: 'draft' | 'submitted' | 'in_review' | 'changes_requested' | 'approved' | 'public' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  summary: string;
  coverImage?: (number | null) | Media;
  locale: 'en' | 'es';
  slug: string;
  translationGroup: string;
  geography?: (number | null) | Taxonomy;
  status: 'draft' | 'public' | 'paused';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-events".
 */
export interface WorkflowEvent {
  id: number;
  article: number | Article;
  actor?: (number | null) | User;
  axis?: ('publication' | 'curation') | null;
  fromStatus?:
    | (
        | 'draft'
        | 'published'
        | 'withdrawn'
        | 'not_selected'
        | 'selected'
        | 'editing'
        | 'curated'
        | 'needs_recheck'
        | 'removed'
        | 'submitted'
        | 'in_review'
        | 'changes_requested'
        | 'approved'
        | 'public'
        | 'archived'
      )
    | null;
  toStatus:
    | 'draft'
    | 'published'
    | 'withdrawn'
    | 'not_selected'
    | 'selected'
    | 'editing'
    | 'curated'
    | 'needs_recheck'
    | 'removed'
    | 'submitted'
    | 'in_review'
    | 'changes_requested'
    | 'approved'
    | 'public'
    | 'archived';
  occurredAt: string;
  notificationKind?: ('selected' | 'major_edit' | 'needs_recheck' | 'removed') | null;
  notificationStatus?: ('not_required' | 'pending' | 'sent' | 'failed') | null;
  notificationKey?: string | null;
  notificationRecipient?: string | null;
  notificationAttempts?: number | null;
  notificationLastError?: string | null;
  notificationSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'person-revisions';
        value: number | PersonRevision;
      } | null)
    | ({
        relationTo: 'taxonomies';
        value: number | Taxonomy;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'workflow-events';
        value: number | WorkflowEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  accountStatus?: T;
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  portrait?: T;
  languages?: T;
  topics?: T;
  identity?: T;
  city?: T;
  introduction?: T;
  identityEs?: T;
  cityEs?: T;
  introductionEs?: T;
  links?:
    | T
    | {
        type?: T;
        label?: T;
        labelEs?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  user?: T;
  profileStatus?: T;
  authorApprovalRecordedAt?: T;
  profilePublishedAt?: T;
  spotlightExcluded?: T;
  spotlightPinnedUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person-revisions_select".
 */
export interface PersonRevisionsSelect<T extends boolean = true> {
  person?: T;
  proposer?: T;
  openPersonKey?: T;
  proposedIdentity?: T;
  proposedIntroduction?: T;
  proposedCity?: T;
  proposedPortrait?: T;
  proposedLanguages?: T;
  proposedTopics?: T;
  proposedLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  status?: T;
  editorNote?: T;
  submittedAt?: T;
  reviewedAt?: T;
  reviewer?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomies_select".
 */
export interface TaxonomiesSelect<T extends boolean = true> {
  dimension?: T;
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  memberUsePublishedAt?: T;
  publicUseApprovedAt?: T;
  publicUseApprovedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  coverImage?: T;
  locale?: T;
  slug?: T;
  author?: T;
  format?: T;
  purposes?: T;
  topics?: T;
  geographies?: T;
  situations?: T;
  sourceNotes?:
    | T
    | {
        label?: T;
        url?: T;
        check?: T;
        id?: T;
      };
  editorComments?:
    | T
    | {
        anchor?: T;
        message?: T;
        resolved?: T;
        createdBy?: T;
        id?: T;
      };
  assignedEditor?: T;
  freshnessDate?: T;
  publishedAt?: T;
  homepagePlacement?: T;
  homepageStartsAt?: T;
  homepageEndsAt?: T;
  translationGroup?: T;
  owner?: T;
  publicationStatus?: T;
  curationStatus?: T;
  workflowStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  coverImage?: T;
  locale?: T;
  slug?: T;
  translationGroup?: T;
  geography?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-events_select".
 */
export interface WorkflowEventsSelect<T extends boolean = true> {
  article?: T;
  actor?: T;
  axis?: T;
  fromStatus?: T;
  toStatus?: T;
  occurredAt?: T;
  notificationKind?: T;
  notificationStatus?: T;
  notificationKey?: T;
  notificationRecipient?: T;
  notificationAttempts?: T;
  notificationLastError?: T;
  notificationSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspace_widget".
 */
export interface WorkspaceWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}