import type { CollectionConfig } from "payload";

import {
  authenticatedField,
  authorField,
  editorialField,
  readOwnPersonRevisionsOrEditorial,
} from "@/cms/access";
import {
  enforcePersonRevisionWorkflow,
  preparePersonRevision,
} from "@/cms/person-revision-hooks";
import { personRevisionDefaults } from "@/cms/person-revision-defaults";

export const PersonRevisions: CollectionConfig = {
  slug: "person-revisions",
  labels: { singular: "Profile revision", plural: "Profile revisions" },
  admin: {
    defaultColumns: ["person", "status", "submittedAt", "updatedAt"],
    group: "People",
    hideAPIURL: true,
    useAsTitle: "person",
    hidden: true,
  },
  access: {
    create: () => false,
    delete: () => false,
    read: readOwnPersonRevisionsOrEditorial,
    update: () => false,
  },
  hooks: {
    beforeChange: [enforcePersonRevisionWorkflow],
    beforeValidate: [preparePersonRevision],
  },
  fields: [
    {
      name: "person",
      type: "relationship",
      relationTo: "people",
      required: true,
      defaultValue: personRevisionDefaults.person,
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { readOnly: true },
    },
    {
      name: "proposer",
      type: "relationship",
      relationTo: "users",
      required: true,
      defaultValue: personRevisionDefaults.proposer,
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { position: "sidebar", readOnly: true },
    },
    {
      name: "openPersonKey",
      type: "text",
      unique: true,
      access: { create: () => false, read: () => false, update: () => false },
      admin: { hidden: true },
    },
    {
      name: "proposedIdentity",
      type: "text",
      required: true,
      label: "Identity",
      defaultValue: personRevisionDefaults.proposedIdentity,
      access: { create: authorField, read: authenticatedField, update: authorField },
    },
    {
      name: "proposedIntroduction",
      type: "textarea",
      required: true,
      label: "Introduction",
      defaultValue: personRevisionDefaults.proposedIntroduction,
      access: { create: authorField, read: authenticatedField, update: authorField },
    },
    {
      name: "proposedCity",
      type: "text",
      required: true,
      label: "City",
      defaultValue: personRevisionDefaults.proposedCity,
      access: { create: authorField, read: authenticatedField, update: authorField },
    },
    {
      name: "proposedPortrait",
      type: "upload",
      relationTo: "media",
      label: "Portrait",
      defaultValue: personRevisionDefaults.proposedPortrait,
      access: { create: authorField, read: authenticatedField, update: authorField },
    },
    {
      name: "proposedLanguages",
      type: "select",
      hasMany: true,
      required: true,
      label: "Languages",
      defaultValue: personRevisionDefaults.proposedLanguages,
      access: { create: authorField, read: authenticatedField, update: authorField },
      options: [
        { label: "English", value: "en" },
        { label: "Spanish", value: "es" },
      ],
    },
    {
      name: "proposedTopics",
      type: "relationship",
      relationTo: "taxonomies",
      hasMany: true,
      label: "Topics",
      defaultValue: personRevisionDefaults.proposedTopics,
      access: { create: authorField, read: authenticatedField, update: authorField },
      filterOptions: { dimension: { equals: "topic" } },
    },
    {
      name: "proposedLinks",
      type: "array",
      maxRows: 8,
      label: "Links",
      defaultValue: personRevisionDefaults.proposedLinks,
      access: { create: authorField, read: authenticatedField, update: authorField },
      fields: [
        { name: "label", type: "text", required: true },
        { name: "url", type: "text", required: true },
      ],
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "draft",
      access: { create: () => false, read: authenticatedField, update: authenticatedField },
      options: [
        { label: "Draft", value: "draft" },
        { label: "Submitted", value: "submitted" },
        { label: "Changes requested", value: "changes_requested" },
        { label: "Applied", value: "applied" },
      ],
      admin: { position: "sidebar" },
    },
    {
      name: "editorNote",
      type: "textarea",
      label: "Editor note",
      access: { create: editorialField, read: authenticatedField, update: editorialField },
    },
    {
      name: "submittedAt",
      type: "date",
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { position: "sidebar", readOnly: true },
    },
    {
      name: "reviewedAt",
      type: "date",
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { position: "sidebar", readOnly: true },
    },
    {
      name: "reviewer",
      type: "relationship",
      relationTo: "users",
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { position: "sidebar", readOnly: true },
    },
    {
      name: "appliedAt",
      type: "date",
      access: { create: () => false, read: authenticatedField, update: () => false },
      admin: { position: "sidebar", readOnly: true },
    },
  ],
};
